function fka_fcn = fka_fcn_order_4(in1,in2,s,d)
%FKA_FCN_ORDER_4
%    FKA_FCN = FKA_FCN_ORDER_4(IN1,IN2,S,D)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    30-Oct-2024 17:50:45

D = in1(4,:);
L = in1(3,:);
phi = in2(8,:);
theta_0 = in2(1,:);
theta_1 = in2(2,:);
theta_2 = in2(3,:);
theta_3 = in2(4,:);
theta_4 = in2(5,:);
x = in2(6,:);
z = in2(7,:);
t2 = integral(@(v)sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_3.*v.^4)./4.0+(theta_4.*v.^5)./5.0),0.0,s);
t3 = integral(@(v)cos(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_3.*v.^4)./4.0+(theta_4.*v.^5)./5.0),0.0,s);
t4 = cos(phi);
t5 = sin(phi);
t6 = L.*t2;
t7 = L.*t3;
t8 = s.*theta_0;
t9 = s.^2;
t10 = s.^3;
t12 = s.^5;
t11 = t9.^2;
t13 = (t9.*theta_1)./2.0;
t14 = (t10.*theta_2)./3.0;
t16 = (t12.*theta_4)./5.0;
t15 = (t11.*theta_3)./4.0;
t17 = t8+t13+t14+t15+t16;
t18 = cos(t17);
t19 = sin(t17);
t20 = D.*d.*t18;
t21 = D.*d.*t19;
t22 = -t20;
t23 = t7+t21;
t24 = t6+t22;
fka_fcn = [x-t4.*t24-t5.*t23;z-t4.*t23+t5.*t24;phi+t17];
end
