function G_fcn = G_fcn(in1,in2)
%G_fcn
%    G_fcn = G_fcn(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    08-Nov-2024 17:30:04

L = in1(3,:);
m_E = in1(2,:);
m_L = in1(1,:);
theta_0 = in2(1,:);
theta_1 = in2(2,:);
theta_2 = in2(3,:);
theta_3 = in2(4,:);
theta_4 = in2(5,:);
t14 = integral(@(v)v.^2.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_3.*v.^4)./4.0+(theta_4.*v.^5)./5.0).*(-1.0./2.0),0.0,7.0./1.2e+1);
t20 = integral(@(v)v.^3.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_3.*v.^4)./4.0+(theta_4.*v.^5)./5.0).*(-1.0./3.0),0.0,5.0./1.2e+1);
t33 = integral(@(v)v.^5.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_3.*v.^4)./4.0+(theta_4.*v.^5)./5.0).*(-1.0./5.0),0.0,1.0./1.2e+1);
t21 = integral(@(v)v.^3.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_3.*v.^4)./4.0+(theta_4.*v.^5)./5.0).*(-1.0./3.0),0.0,7.0./1.2e+1);
t27 = integral(@(v)v.^4.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_3.*v.^4)./4.0+(theta_4.*v.^5)./5.0).*(-1.0./4.0),0.0,5.0./1.2e+1);
t15 = integral(@(v)v.^2.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_3.*v.^4)./4.0+(theta_4.*v.^5)./5.0).*(-1.0./2.0),0.0,1.1e+1./1.2e+1);
t28 = integral(@(v)v.^4.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_3.*v.^4)./4.0+(theta_4.*v.^5)./5.0).*(-1.0./4.0),0.0,7.0./1.2e+1);
t34 = integral(@(v)v.^5.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_3.*v.^4)./4.0+(theta_4.*v.^5)./5.0).*(-1.0./5.0),0.0,5.0./1.2e+1);
t22 = integral(@(v)v.^3.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_3.*v.^4)./4.0+(theta_4.*v.^5)./5.0).*(-1.0./3.0),0.0,1.1e+1./1.2e+1);
t35 = integral(@(v)v.^5.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_3.*v.^4)./4.0+(theta_4.*v.^5)./5.0).*(-1.0./5.0),0.0,7.0./1.2e+1);
t29 = integral(@(v)v.^4.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_3.*v.^4)./4.0+(theta_4.*v.^5)./5.0).*(-1.0./4.0),0.0,1.1e+1./1.2e+1);
t36 = integral(@(v)v.^5.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_3.*v.^4)./4.0+(theta_4.*v.^5)./5.0).*(-1.0./5.0),0.0,1.1e+1./1.2e+1);
t2 = integral(@(v)-v.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_3.*v.^4)./4.0+(theta_4.*v.^5)./5.0),0.0,1.0);
t3 = integral(@(v)-v.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_3.*v.^4)./4.0+(theta_4.*v.^5)./5.0),0.0,1.0./4.0);
t4 = integral(@(v)-v.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_3.*v.^4)./4.0+(theta_4.*v.^5)./5.0),0.0,3.0./4.0);
t5 = integral(@(v)-v.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_3.*v.^4)./4.0+(theta_4.*v.^5)./5.0),0.0,1.0./1.2e+1);
t6 = integral(@(v)-v.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_3.*v.^4)./4.0+(theta_4.*v.^5)./5.0),0.0,5.0./1.2e+1);
t7 = integral(@(v)-v.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_3.*v.^4)./4.0+(theta_4.*v.^5)./5.0),0.0,7.0./1.2e+1);
t8 = integral(@(v)-v.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_3.*v.^4)./4.0+(theta_4.*v.^5)./5.0),0.0,1.1e+1./1.2e+1);
t9 = integral(@(v)v.^2.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_3.*v.^4)./4.0+(theta_4.*v.^5)./5.0).*(-1.0./2.0),0.0,1.0);
t16 = integral(@(v)v.^3.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_3.*v.^4)./4.0+(theta_4.*v.^5)./5.0).*(-1.0./3.0),0.0,1.0);
t10 = integral(@(v)v.^2.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_3.*v.^4)./4.0+(theta_4.*v.^5)./5.0).*(-1.0./2.0),0.0,1.0./4.0);
t23 = integral(@(v)v.^4.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_3.*v.^4)./4.0+(theta_4.*v.^5)./5.0).*(-1.0./4.0),0.0,1.0);
t11 = integral(@(v)v.^2.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_3.*v.^4)./4.0+(theta_4.*v.^5)./5.0).*(-1.0./2.0),0.0,3.0./4.0);
t17 = integral(@(v)v.^3.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_3.*v.^4)./4.0+(theta_4.*v.^5)./5.0).*(-1.0./3.0),0.0,1.0./4.0);
t30 = integral(@(v)v.^5.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_3.*v.^4)./4.0+(theta_4.*v.^5)./5.0).*(-1.0./5.0),0.0,1.0);
t18 = integral(@(v)v.^3.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_3.*v.^4)./4.0+(theta_4.*v.^5)./5.0).*(-1.0./3.0),0.0,3.0./4.0);
t24 = integral(@(v)v.^4.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_3.*v.^4)./4.0+(theta_4.*v.^5)./5.0).*(-1.0./4.0),0.0,1.0./4.0);
t25 = integral(@(v)v.^4.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_3.*v.^4)./4.0+(theta_4.*v.^5)./5.0).*(-1.0./4.0),0.0,3.0./4.0);
t31 = integral(@(v)v.^5.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_3.*v.^4)./4.0+(theta_4.*v.^5)./5.0).*(-1.0./5.0),0.0,1.0./4.0);
t12 = integral(@(v)v.^2.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_3.*v.^4)./4.0+(theta_4.*v.^5)./5.0).*(-1.0./2.0),0.0,1.0./1.2e+1);
t32 = integral(@(v)v.^5.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_3.*v.^4)./4.0+(theta_4.*v.^5)./5.0).*(-1.0./5.0),0.0,3.0./4.0);
t19 = integral(@(v)v.^3.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_3.*v.^4)./4.0+(theta_4.*v.^5)./5.0).*(-1.0./3.0),0.0,1.0./1.2e+1);
t13 = integral(@(v)v.^2.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_3.*v.^4)./4.0+(theta_4.*v.^5)./5.0).*(-1.0./2.0),0.0,5.0./1.2e+1);
t26 = integral(@(v)v.^4.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_3.*v.^4)./4.0+(theta_4.*v.^5)./5.0).*(-1.0./4.0),0.0,1.0./1.2e+1);
mt1 = [L.*m_E.*conj(t2).*(-9.81e+2./1.0e+2)-L.*m_L.*conj(t3).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t4).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t5).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t6).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t7).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t8).*(3.27e+2./2.0e+2);L.*m_E.*conj(t9).*(-9.81e+2./1.0e+2)-L.*m_L.*conj(t10).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t11).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t12).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t13).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t14).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t15).*(3.27e+2./2.0e+2)];
mt2 = [L.*m_E.*conj(t16).*(-9.81e+2./1.0e+2)-L.*m_L.*conj(t17).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t18).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t19).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t20).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t21).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t22).*(3.27e+2./2.0e+2);L.*m_E.*conj(t23).*(-9.81e+2./1.0e+2)-L.*m_L.*conj(t24).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t25).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t26).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t27).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t28).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t29).*(3.27e+2./2.0e+2)];
mt3 = [L.*m_E.*conj(t30).*(-9.81e+2./1.0e+2)-L.*m_L.*conj(t31).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t32).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t33).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t34).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t35).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t36).*(3.27e+2./2.0e+2)];
G_fcn = [mt1;mt2;mt3];
end
