function fk_fcn = fk_fcn(in1,in2,s,d)
%FK_FCN
%    FK_FCN = FK_FCN(IN1,IN2,S,D)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    08-Nov-2024 17:19:19

D = in1(4,:);
L = in1(3,:);
theta_0 = in2(1,:);
theta_1 = in2(2,:);
theta_2 = in2(3,:);
t2 = integral(@(v)sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0),0.0,s);
t3 = integral(@(v)cos(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0),0.0,s);
t4 = s.*theta_0;
t5 = s.^2;
t6 = s.^3;
t7 = (t5.*theta_1)./2.0;
t8 = (t6.*theta_2)./3.0;
t9 = t4+t7+t8;
fk_fcn = [-L.*t2+D.*d.*cos(t9);-L.*t3-D.*d.*sin(t9)];
end
