function G_fcn = G_fcn(in1,in2)
%G_fcn
%    G_fcn = G_fcn(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    08-Nov-2024 17:19:19

L = in1(3,:);
m_E = in1(2,:);
m_L = in1(1,:);
theta_0 = in2(1,:);
theta_1 = in2(2,:);
theta_2 = in2(3,:);
t9 = integral(@(v)v.^2.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0).*(-1.0./2.0),0.0,1.0);
t16 = integral(@(v)v.^3.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0).*(-1.0./3.0),0.0,1.0);
t10 = integral(@(v)v.^2.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0).*(-1.0./2.0),0.0,1.0./4.0);
t11 = integral(@(v)v.^2.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0).*(-1.0./2.0),0.0,3.0./4.0);
t17 = integral(@(v)v.^3.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0).*(-1.0./3.0),0.0,1.0./4.0);
t18 = integral(@(v)v.^3.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0).*(-1.0./3.0),0.0,3.0./4.0);
t12 = integral(@(v)v.^2.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0).*(-1.0./2.0),0.0,1.0./1.2e+1);
t19 = integral(@(v)v.^3.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0).*(-1.0./3.0),0.0,1.0./1.2e+1);
t13 = integral(@(v)v.^2.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0).*(-1.0./2.0),0.0,5.0./1.2e+1);
t14 = integral(@(v)v.^2.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0).*(-1.0./2.0),0.0,7.0./1.2e+1);
t20 = integral(@(v)v.^3.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0).*(-1.0./3.0),0.0,5.0./1.2e+1);
t21 = integral(@(v)v.^3.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0).*(-1.0./3.0),0.0,7.0./1.2e+1);
t15 = integral(@(v)v.^2.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0).*(-1.0./2.0),0.0,1.1e+1./1.2e+1);
t22 = integral(@(v)v.^3.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0).*(-1.0./3.0),0.0,1.1e+1./1.2e+1);
t2 = integral(@(v)-v.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0),0.0,1.0);
t3 = integral(@(v)-v.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0),0.0,1.0./4.0);
t4 = integral(@(v)-v.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0),0.0,3.0./4.0);
t5 = integral(@(v)-v.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0),0.0,1.0./1.2e+1);
t6 = integral(@(v)-v.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0),0.0,5.0./1.2e+1);
t7 = integral(@(v)-v.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0),0.0,7.0./1.2e+1);
t8 = integral(@(v)-v.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0),0.0,1.1e+1./1.2e+1);
mt1 = [L.*m_E.*conj(t2).*(-9.81e+2./1.0e+2)-L.*m_L.*conj(t3).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t4).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t5).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t6).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t7).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t8).*(3.27e+2./2.0e+2);L.*m_E.*conj(t9).*(-9.81e+2./1.0e+2)-L.*m_L.*conj(t10).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t11).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t12).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t13).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t14).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t15).*(3.27e+2./2.0e+2)];
mt2 = [L.*m_E.*conj(t16).*(-9.81e+2./1.0e+2)-L.*m_L.*conj(t17).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t18).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t19).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t20).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t21).*(3.27e+2./2.0e+2)-L.*m_L.*conj(t22).*(3.27e+2./2.0e+2)];
G_fcn = [mt1;mt2];
end
