function Gv_fcn = Gv_fcn(in1,in2,gamma)
%Gv_fcn
%    Gv_fcn = Gv_fcn(IN1,IN2,GAMMA)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    08-Nov-2024 17:19:19

L = in1(3,:);
m_E = in1(2,:);
m_L = in1(1,:);
theta_0 = in2(1,:);
theta_1 = in2(2,:);
theta_2 = in2(3,:);
t16 = integral(@(v)v.^2.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0).*(-1.0./2.0),0.0,1.0);
t30 = integral(@(v)v.^3.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0).*(-1.0./3.0),0.0,1.0);
t18 = integral(@(v)v.^2.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0).*(-1.0./2.0),0.0,1.0./4.0);
t20 = integral(@(v)v.^2.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0).*(-1.0./2.0),0.0,3.0./4.0);
t32 = integral(@(v)v.^3.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0).*(-1.0./3.0),0.0,1.0./4.0);
t34 = integral(@(v)v.^3.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0).*(-1.0./3.0),0.0,3.0./4.0);
t22 = integral(@(v)v.^2.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0).*(-1.0./2.0),0.0,1.0./1.2e+1);
t36 = integral(@(v)v.^3.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0).*(-1.0./3.0),0.0,1.0./1.2e+1);
t24 = integral(@(v)v.^2.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0).*(-1.0./2.0),0.0,5.0./1.2e+1);
t26 = integral(@(v)v.^2.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0).*(-1.0./2.0),0.0,7.0./1.2e+1);
t38 = integral(@(v)v.^3.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0).*(-1.0./3.0),0.0,5.0./1.2e+1);
t40 = integral(@(v)v.^3.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0).*(-1.0./3.0),0.0,7.0./1.2e+1);
t28 = integral(@(v)v.^2.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0).*(-1.0./2.0),0.0,1.1e+1./1.2e+1);
t42 = integral(@(v)v.^3.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0).*(-1.0./3.0),0.0,1.1e+1./1.2e+1);
t17 = integral(@(v)(v.^2.*cos(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0))./2.0,0.0,1.0);
t31 = integral(@(v)(v.^3.*cos(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0))./3.0,0.0,1.0);
t19 = integral(@(v)(v.^2.*cos(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0))./2.0,0.0,1.0./4.0);
t21 = integral(@(v)(v.^2.*cos(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0))./2.0,0.0,3.0./4.0);
t33 = integral(@(v)(v.^3.*cos(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0))./3.0,0.0,1.0./4.0);
t35 = integral(@(v)(v.^3.*cos(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0))./3.0,0.0,3.0./4.0);
t23 = integral(@(v)(v.^2.*cos(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0))./2.0,0.0,1.0./1.2e+1);
t37 = integral(@(v)(v.^3.*cos(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0))./3.0,0.0,1.0./1.2e+1);
t25 = integral(@(v)(v.^2.*cos(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0))./2.0,0.0,5.0./1.2e+1);
t27 = integral(@(v)(v.^2.*cos(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0))./2.0,0.0,7.0./1.2e+1);
t39 = integral(@(v)(v.^3.*cos(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0))./3.0,0.0,5.0./1.2e+1);
t41 = integral(@(v)(v.^3.*cos(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0))./3.0,0.0,7.0./1.2e+1);
t29 = integral(@(v)(v.^2.*cos(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0))./2.0,0.0,1.1e+1./1.2e+1);
t43 = integral(@(v)(v.^3.*cos(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0))./3.0,0.0,1.1e+1./1.2e+1);
t3 = integral(@(v)-v.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0),0.0,1.0);
t5 = integral(@(v)-v.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0),0.0,1.0./4.0);
t7 = integral(@(v)-v.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0),0.0,3.0./4.0);
t9 = integral(@(v)-v.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0),0.0,1.0./1.2e+1);
t11 = integral(@(v)-v.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0),0.0,5.0./1.2e+1);
t13 = integral(@(v)-v.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0),0.0,7.0./1.2e+1);
t15 = integral(@(v)-v.*sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0),0.0,1.1e+1./1.2e+1);
t2 = integral(@(v)v.*cos(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0),0.0,1.0);
t4 = integral(@(v)v.*cos(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0),0.0,1.0./4.0);
t6 = integral(@(v)v.*cos(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0),0.0,3.0./4.0);
t8 = integral(@(v)v.*cos(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0),0.0,1.0./1.2e+1);
t10 = integral(@(v)v.*cos(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0),0.0,5.0./1.2e+1);
t12 = integral(@(v)v.*cos(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0),0.0,7.0./1.2e+1);
t14 = integral(@(v)v.*cos(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0),0.0,1.1e+1./1.2e+1);
t44 = conj(gamma);
t45 = cos(t44);
t46 = sin(t44);
mt1 = [m_E.*(L.*t45.*conj(t3)+L.*t46.*conj(t2)).*(-9.81e+2./1.0e+2)-m_L.*(L.*t45.*conj(t5)+L.*t46.*conj(t4)).*(3.27e+2./2.0e+2)-m_L.*(L.*t45.*conj(t7)+L.*t46.*conj(t6)).*(3.27e+2./2.0e+2)-m_L.*(L.*t45.*conj(t9)+L.*t46.*conj(t8)).*(3.27e+2./2.0e+2)-m_L.*(L.*t45.*conj(t11)+L.*t46.*conj(t10)).*(3.27e+2./2.0e+2)-m_L.*(L.*t45.*conj(t13)+L.*t46.*conj(t12)).*(3.27e+2./2.0e+2)-m_L.*(L.*t45.*conj(t15)+L.*t46.*conj(t14)).*(3.27e+2./2.0e+2)];
mt2 = [m_E.*(L.*t45.*conj(t16)+L.*t46.*conj(t17)).*(-9.81e+2./1.0e+2)-m_L.*(L.*t45.*conj(t18)+L.*t46.*conj(t19)).*(3.27e+2./2.0e+2)-m_L.*(L.*t45.*conj(t20)+L.*t46.*conj(t21)).*(3.27e+2./2.0e+2)-m_L.*(L.*t45.*conj(t22)+L.*t46.*conj(t23)).*(3.27e+2./2.0e+2)-m_L.*(L.*t45.*conj(t24)+L.*t46.*conj(t25)).*(3.27e+2./2.0e+2)-m_L.*(L.*t45.*conj(t26)+L.*t46.*conj(t27)).*(3.27e+2./2.0e+2)-m_L.*(L.*t45.*conj(t28)+L.*t46.*conj(t29)).*(3.27e+2./2.0e+2)];
mt3 = [m_E.*(L.*t45.*conj(t30)+L.*t46.*conj(t31)).*(-9.81e+2./1.0e+2)-m_L.*(L.*t45.*conj(t32)+L.*t46.*conj(t33)).*(3.27e+2./2.0e+2)-m_L.*(L.*t45.*conj(t34)+L.*t46.*conj(t35)).*(3.27e+2./2.0e+2)-m_L.*(L.*t45.*conj(t36)+L.*t46.*conj(t37)).*(3.27e+2./2.0e+2)-m_L.*(L.*t45.*conj(t38)+L.*t46.*conj(t39)).*(3.27e+2./2.0e+2)-m_L.*(L.*t45.*conj(t40)+L.*t46.*conj(t41)).*(3.27e+2./2.0e+2)-m_L.*(L.*t45.*conj(t42)+L.*t46.*conj(t43)).*(3.27e+2./2.0e+2)];
Gv_fcn = [mt1;mt2;mt3];
end
