function fka_fcn = fka_fcn_order_2(in1,in2,s,d)
%FKA_FCN_ORDER_2
%    FKA_FCN = FKA_FCN_ORDER_2(IN1,IN2,S,D)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    30-Oct-2024 17:37:10

D = in1(4,:);
L = in1(3,:);
phi = in2(6,:);
theta_0 = in2(1,:);
theta_1 = in2(2,:);
theta_2 = in2(3,:);
x = in2(4,:);
z = in2(5,:);
t2 = integral(@(v)sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0),0.0,s);
t3 = integral(@(v)cos(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0),0.0,s);
t4 = cos(phi);
t5 = sin(phi);
t6 = L.*t2;
t7 = L.*t3;
t8 = s.*theta_0;
t9 = s.^2;
t10 = s.^3;
t11 = (t9.*theta_1)./2.0;
t12 = (t10.*theta_2)./3.0;
t13 = t8+t11+t12;
t14 = cos(t13);
t15 = sin(t13);
t16 = D.*d.*t14;
t17 = D.*d.*t15;
t18 = -t16;
t19 = t7+t17;
t20 = t6+t18;
fka_fcn = [x-t4.*t20-t5.*t19;z-t4.*t19+t5.*t20;phi+t13];
end
