function G_fcn = G_fcn(in1,theta_0)
%G_fcn
%    G_fcn = G_fcn(IN1,THETA_0)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    08-Nov-2024 17:09:37

L = in1(3,:);
m_E = in1(2,:);
m_L = in1(1,:);
t2 = conj(theta_0);
t3 = 1.0./t2;
t5 = t2./4.0;
t6 = t2.*(3.0./4.0);
t7 = t2./1.2e+1;
t8 = t2.*(5.0./1.2e+1);
t9 = t2.*(7.0./1.2e+1);
t10 = t2.*(1.1e+1./1.2e+1);
t4 = t3.^2;
G_fcn = L.*m_E.*t3.*cos(t2).*(-9.81e+2./1.0e+2)-L.*m_L.*t3.*cos(t5).*(3.27e+2./8.0e+2)-L.*m_L.*t3.*cos(t6).*(9.81e+2./8.0e+2)-L.*m_L.*t3.*cos(t7).*(1.09e+2./8.0e+2)-L.*m_L.*t3.*cos(t8).*(1.09e+2./1.6e+2)-L.*m_L.*t3.*cos(t9).*(7.63e+2./8.0e+2)-L.*m_L.*t3.*cos(t10).*1.49875+L.*m_E.*t4.*sin(t2).*(9.81e+2./1.0e+2)+L.*m_L.*t4.*sin(t5).*(3.27e+2./2.0e+2)+L.*m_L.*t4.*sin(t6).*(3.27e+2./2.0e+2)+L.*m_L.*t4.*sin(t7).*(3.27e+2./2.0e+2)+L.*m_L.*t4.*sin(t8).*(3.27e+2./2.0e+2)+L.*m_L.*t4.*sin(t9).*(3.27e+2./2.0e+2)+L.*m_L.*t4.*sin(t10).*(3.27e+2./2.0e+2);
end
