function Gv_fcn = Gv_fcn(in1,theta_0,gamma)
%Gv_fcn
%    Gv_fcn = Gv_fcn(IN1,THETA_0,GAMMA)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    08-Nov-2024 17:09:37

L = in1(3,:);
m_E = in1(2,:);
m_L = in1(1,:);
t2 = conj(gamma);
t3 = conj(theta_0);
t4 = sin(t2);
t5 = -t3;
t6 = 1.0./t3;
t8 = t3./4.0;
t9 = t3.*(3.0./4.0);
t12 = t3./1.2e+1;
t13 = t3.*(5.0./1.2e+1);
t14 = t3.*(7.0./1.2e+1);
t18 = t3.*(1.1e+1./1.2e+1);
t7 = t6.^2;
t10 = -t8;
t11 = -t9;
t15 = -t12;
t16 = -t13;
t17 = -t14;
t19 = t2+t5;
t20 = -t18;
t21 = t2+t10;
t22 = t2+t11;
t23 = t2+t15;
t24 = t2+t16;
t25 = t2+t17;
t26 = t2+t20;
et1 = L.*m_E.*t6.*cos(t19).*(-9.81e+2./1.0e+2)-L.*m_L.*t6.*cos(t21).*(3.27e+2./8.0e+2)-L.*m_L.*t6.*cos(t22).*(9.81e+2./8.0e+2)-L.*m_L.*t6.*cos(t23).*(1.09e+2./8.0e+2)-L.*m_L.*t6.*cos(t24).*(1.09e+2./1.6e+2)-L.*m_L.*t6.*cos(t25).*(7.63e+2./8.0e+2)-L.*m_L.*t6.*cos(t26).*1.49875+L.*m_E.*t7.*(t4-sin(t19)).*(9.81e+2./1.0e+2)+L.*m_L.*t7.*(t4-sin(t21)).*(3.27e+2./2.0e+2)+L.*m_L.*t7.*(t4-sin(t22)).*(3.27e+2./2.0e+2)+L.*m_L.*t7.*(t4-sin(t23)).*(3.27e+2./2.0e+2)+L.*m_L.*t7.*(t4-sin(t24)).*(3.27e+2./2.0e+2);
et2 = L.*m_L.*t7.*(t4-sin(t25)).*(3.27e+2./2.0e+2)+L.*m_L.*t7.*(t4-sin(t26)).*(3.27e+2./2.0e+2);
Gv_fcn = et1+et2;
end
