function ddx = fss_fcn(x,dx)
%
% function ddx = fss_fcn(x,dx)
%
% This function implements simplified dynamics for the purpose of evaluating the steady state 
% leveraging the other functions authomatically generated by model_gen_fixed_base
%

global p_vals G_dir
global K Theta_bar D

if abs(x(1)) < 1e-5
    x(1) = 1e-5;
end

if abs(x(2)) < 1e-5
    x(2) = 1e-5;
end

G = Gv_fcn(p_vals',x,G_dir);

ddx = 1e-3*eye(2)\(-G -K*(x-Theta_bar) -D*dx);