function fka_fcn = fka_fcn_order_5(in1,in2,s,d)
%FKA_FCN_ORDER_5
%    FKA_FCN = FKA_FCN_ORDER_5(IN1,IN2,S,D)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    30-Oct-2024 18:01:18

D = in1(4,:);
L = in1(3,:);
phi = in2(9,:);
theta_0 = in2(1,:);
theta_1 = in2(2,:);
theta_2 = in2(3,:);
theta_3 = in2(4,:);
theta_4 = in2(5,:);
theta_5 = in2(6,:);
x = in2(7,:);
z = in2(8,:);
t2 = integral(@(v)sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_3.*v.^4)./4.0+(theta_4.*v.^5)./5.0+(theta_5.*v.^6)./6.0),0.0,s);
t3 = integral(@(v)cos(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_3.*v.^4)./4.0+(theta_4.*v.^5)./5.0+(theta_5.*v.^6)./6.0),0.0,s);
t4 = cos(phi);
t5 = sin(phi);
t6 = L.*t2;
t7 = L.*t3;
t8 = s.*theta_0;
t9 = s.^2;
t10 = s.^3;
t12 = s.^5;
t11 = t9.^2;
t13 = t9.^3;
t14 = (t9.*theta_1)./2.0;
t15 = (t10.*theta_2)./3.0;
t17 = (t12.*theta_4)./5.0;
t16 = (t11.*theta_3)./4.0;
t18 = (t13.*theta_5)./6.0;
t19 = t8+t14+t15+t16+t17+t18;
t20 = cos(t19);
t21 = sin(t19);
t22 = D.*d.*t20;
t23 = D.*d.*t21;
t24 = -t22;
t25 = t7+t23;
t26 = t6+t24;
fka_fcn = [x-t4.*t26-t5.*t25;z-t4.*t25+t5.*t26;phi+t19];
end
