function fk_fcn = fk_fcn(in1,in2,s,d)
%FK_FCN
%    FK_FCN = FK_FCN(IN1,IN2,S,D)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    28-Apr-2025 21:03:26

D = in1(4,:);
L = in1(3,:);
theta1 = in2(1,:);
theta2 = in2(2,:);
theta3 = in2(3,:);
t2 = integral(@(v)sin(theta1.*v+(theta2.*v.^2)./2.0+(theta3.*v.^3)./6.0),0.0,s);
t3 = integral(@(v)cos(theta1.*v+(theta2.*v.^2)./2.0+(theta3.*v.^3)./6.0),0.0,s);
t4 = s.*theta1;
t5 = s.^2;
t6 = s.^3;
t7 = (t5.*theta2)./2.0;
t8 = (t6.*theta3)./6.0;
t9 = t4+t7+t8;
fk_fcn = [-L.*t2+D.*d.*cos(t9);-L.*t3-D.*d.*sin(t9)];
end
