function J = J_fcn(in1,in2,s,d)
%J_fcn
%    J = J_fcn(IN1,IN2,S,D)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    27-Apr-2025 20:48:37

D = in1(4,:);
L = in1(3,:);
theta1 = in2(1,:);
theta2 = in2(2,:);
theta3 = in2(3,:);
t2 = integral(@(v)v.*cos(theta1.*v+(theta2.*v.^2)./2.0+(theta3.*v.^3)./6.0),0.0,s);
t3 = integral(@(v)(v.^2.*cos(theta1.*v+(theta2.*v.^2)./2.0+(theta3.*v.^3)./6.0))./2.0,0.0,s);
t4 = integral(@(v)(v.^3.*cos(theta1.*v+(theta2.*v.^2)./2.0+(theta3.*v.^3)./6.0))./6.0,0.0,s);
t5 = integral(@(v)-v.*sin(theta1.*v+(theta2.*v.^2)./2.0+(theta3.*v.^3)./6.0),0.0,s);
t6 = integral(@(v)v.^2.*sin(theta1.*v+(theta2.*v.^2)./2.0+(theta3.*v.^3)./6.0).*(-1.0./2.0),0.0,s);
t7 = integral(@(v)v.^3.*sin(theta1.*v+(theta2.*v.^2)./2.0+(theta3.*v.^3)./6.0).*(-1.0./6.0),0.0,s);
t8 = s.*theta1;
t9 = s.^2;
t10 = s.^3;
t11 = (t9.*theta2)./2.0;
t12 = (t10.*theta3)./6.0;
t13 = t8+t11+t12;
t14 = cos(t13);
t15 = sin(t13);
J = reshape([-L.*t2-D.*d.*s.*t15,-L.*t5-D.*d.*s.*t14,-L.*t3-(D.*d.*t9.*t15)./2.0,-L.*t6-(D.*d.*t9.*t14)./2.0,-L.*t4-(D.*d.*t10.*t15)./6.0,-L.*t7-(D.*d.*t10.*t14)./6.0],[2,3]);
end
