function fka_fcn = fka_fcn_order_0(in1,in2,s,d)
%FKA_FCN_ORDER_0
%    FKA_FCN = FKA_FCN_ORDER_0(IN1,IN2,S,D)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    30-Oct-2024 17:25:37

D = in1(4,:);
L = in1(3,:);
phi = in2(4,:);
theta_0 = in2(1,:);
x = in2(2,:);
z = in2(3,:);
t2 = cos(phi);
t3 = sin(phi);
t4 = s.*theta_0;
t7 = 1.0./theta_0;
t5 = cos(t4);
t6 = sin(t4);
t8 = t4./2.0;
t9 = D.*d.*t5;
t10 = sin(t8);
t11 = D.*d.*t6;
t14 = L.*t6.*t7;
t12 = t10.^2;
t16 = t11+t14;
t15 = L.*t7.*t12.*2.0;
fka_fcn = [x-t3.*t16+t2.*(t9-t15);z-t2.*t16-t3.*(t9-t15);phi+t4];
end
