function G_fcn = G_fcn(in1,in2)
%G_fcn
%    G_fcn = G_fcn(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    29-Oct-2024 16:39:15

L = in1(3,:);
m_E = in1(2,:);
m_L = in1(1,:);
phi = in2(4,:);
theta_0 = in2(1,:);
t2 = cos(phi);
t3 = sin(phi);
t4 = phi+theta_0;
t8 = 1.0./theta_0;
t10 = theta_0./4.0;
t11 = theta_0.*(3.0./4.0);
t12 = theta_0./1.2e+1;
t13 = theta_0.*(5.0./1.2e+1);
t14 = theta_0.*(7.0./1.2e+1);
t17 = theta_0.*(1.1e+1./1.2e+1);
t5 = L.*t2;
t6 = L.*t3;
t7 = cos(t4);
t9 = t8.^2;
t15 = phi+t10;
t16 = phi+t11;
t20 = phi+t12;
t21 = phi+t13;
t22 = phi+t14;
t26 = phi+t17;
t18 = cos(t15);
t19 = cos(t16);
t23 = cos(t20);
t24 = cos(t21);
t25 = cos(t22);
t27 = cos(t26);
mt1 = [m_E.*(t9.*(t6-L.*sin(t4))+L.*t7.*t8).*(-9.81e+2./1.0e+2)-m_L.*(t9.*(t6-L.*sin(t15))+(L.*t8.*t18)./4.0).*(3.27e+2./2.0e+2)-m_L.*(t9.*(t6-L.*sin(t16))+L.*t8.*t19.*(3.0./4.0)).*(3.27e+2./2.0e+2)-m_L.*(t9.*(t6-L.*sin(t20))+(L.*t8.*t23)./1.2e+1).*(3.27e+2./2.0e+2)-m_L.*(t9.*(t6-L.*sin(t21))+L.*t8.*t24.*(5.0./1.2e+1)).*(3.27e+2./2.0e+2)-m_L.*(t9.*(t6-L.*sin(t22))+L.*t8.*t25.*(7.0./1.2e+1)).*(3.27e+2./2.0e+2)-m_L.*(t9.*(t6-L.*sin(t26))+L.*t8.*t27.*(1.1e+1./1.2e+1)).*(3.27e+2./2.0e+2)];
mt2 = [0.0;m_E.*(9.81e+2./1.0e+2)+m_L.*(9.81e+2./1.0e+2)+7.848e-1;m_E.*t8.*(t5-L.*t7).*(9.81e+2./1.0e+2)+m_L.*t8.*(t5-L.*t18).*(3.27e+2./2.0e+2)+m_L.*t8.*(t5-L.*t19).*(3.27e+2./2.0e+2)+m_L.*t8.*(t5-L.*t23).*(3.27e+2./2.0e+2)+m_L.*t8.*(t5-L.*t24).*(3.27e+2./2.0e+2)+m_L.*t8.*(t5-L.*t25).*(3.27e+2./2.0e+2)+m_L.*t8.*(t5-L.*t27).*(3.27e+2./2.0e+2)];
G_fcn = [mt1;mt2];
end
