function fk_fcn = fk_fcn(in1,theta_0,s,d)
%FK_FCN
%    FK_FCN = FK_FCN(IN1,THETA_0,S,D)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    08-Nov-2024 17:09:36

D = in1(4,:);
L = in1(3,:);
t2 = s.*theta_0;
t4 = 1.0./theta_0;
t3 = sin(t2);
fk_fcn = [L.*t4.*sin(t2./2.0).^2.*-2.0+D.*d.*cos(t2);-D.*d.*t3-L.*t3.*t4];
end
