function fka_fcn = fka_fcn(in1,in2,s,d)
%FKA_FCN
%    FKA_FCN = FKA_FCN(IN1,IN2,S,D)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    29-Oct-2024 17:30:47

D = in1(4,:);
L = in1(3,:);
phi = in2(7,:);
theta_0 = in2(1,:);
theta_1 = in2(2,:);
theta_2 = in2(3,:);
x = in2(5,:);
z = in2(6,:);
t2 = integral(@(v)sin(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_2.*v.^4)./4.0),0.0,s);
t3 = integral(@(v)cos(theta_0.*v+(theta_1.*v.^2)./2.0+(theta_2.*v.^3)./3.0+(theta_2.*v.^4)./4.0),0.0,s);
t4 = cos(phi);
t5 = sin(phi);
t6 = L.*t2;
t7 = L.*t3;
t8 = s.*theta_0;
t9 = s.^2;
t10 = s.^3;
t11 = t9.^2;
t12 = (t9.*theta_1)./2.0;
t13 = (t10.*theta_2)./3.0;
t14 = (t11.*theta_2)./4.0;
t15 = t8+t12+t13+t14;
t16 = sin(t15);
t17 = cos(t15);
t18 = D.*d.*t17;
t19 = D.*d.*t16;
t20 = -t18;
t21 = t7+t19;
t22 = t6+t20;
fka_fcn = [x-t4.*t22-t5.*t21;z-t4.*t21+t5.*t22;phi+t15];
end
