function ddx = f_fcn(x,dx,F)
%
% function ddx = f_fcn(x,dx,F)
%
% This function implements the dynamics leveraging the other functions
%  authomatically generated by model_gen
%

global K Theta_bar D p_vals
global G_Scale B_Scale

if abs(x(1)) < 1e-5
    x(1) = 1e-5;
end

if abs(x(2)) < 1e-5
    x(2) = 1e-5;
end

B = B_fcn(p_vals',x);
G = Gv_fcn(p_vals',x,0);
% C = C_fcn(p_vals',x,dx);

ddx = B*B_Scale\(-G*G_Scale -K*(x-Theta_bar) -D*dx + [0; 0; F(1); F(2); F(3)]);  % without Coriolis/centrifugal
% ddx = B*B_Scale\(-C*dx -G*G_Scale -K*(x-Theta_bar) -D*dx + [0; 0; F(1); F(2); F(3)]);  % without Coriolis/centrifugal